jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@v3.18
        with:
          config_timezone: Europe/Sofia
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_reactions: yes
          token: ${{ secrets.GIT_HUB_TOKEN }}
name: Metrics
'on':
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
