jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@v3.18
        with:
          config_timezone: Europe/Sofia
          plugin_achievements: 'yes'
          plugin_achievements_limit: 10
          plugin_achievements_secrets: 'yes'
          plugin_activity: 'yes'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'yes'
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: 'yes'
          plugin_stargazers: 'yes'
          token: ${{ secrets.GITHUB_TOKEN }}
name: Metrics
'on':
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
